# Generated by Django 4.0.8 on 2023-06-12 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 12, 3, 12, 53, 41064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 12, 3, 12, 53, 41319, tzinfo=utc)),
        ),
    ]
