# Generated by Django 4.0.8 on 2023-06-12 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_created_at_alter_courses_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 11, 36, 26, 502199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 11, 36, 26, 502453, tzinfo=utc)),
        ),
    ]
